### ISSUE TITLE
Kaartlagen en views maken om toe te voegen

### ISSUE THREAD

**Issue by bastiaan-roos** [hhnk-git/legger#12]
Onder andere:
- [x] iets met styling op m ivm breedte (wouter)
- [x] nog wat meer kaartlagen, ook met resultaten
- [x] op kaart aangeven waar profiel is ingevuld
- [x] gekozen begroeiingsgraad

**Comment by stuart-minion** [comment]
Zie screen voor volgorde

![image](https://user-images.githubusercontent.com/48908991/56205833-29b43380-604b-11e9-9615-c141b75a5414.png)

**Comment by stuart-minion** [comment]
[styling.zip](https://github.com/hhnk-git/legger/files/3084707/styling.zip)

**Comment by bastiaan-roos** [comment]
ok, ik ga ermee verder

**Comment by stuart-minion** [comment]
Nieuwe styling met onderscheid gemeten of theoretisch profiel
[styling_v2.zip](https://github.com/hhnk-git/legger/files/3088949/styling_v2.zip)

**Comment by stuart-minion** [comment]
@bastiaan-roos ik denk dat de gekozen begroeiing nog niet in de view zit hydroobjects_selected_legger, kun jij die view nog aanpassen?

**Comment by bastiaan-roos** [comment]
zit in de laatste master. let wel op, nieuwe kolommen in de views komen niet altijd goed door in bestaande databases.
