### ISSUE TITLE
verschillende kleine verbeteringen

### ISSUE THREAD

**Issue by bastiaan-roos** [hhnk-git/legger#18]
- [x] geneste gebieden sluiten niet altijd aan... / liggen op verkeerde plek
- [x] Opstuwnorm koppelen
- [x] styling updaten voor hydrovakken zonder gemeten profielen (aangeleverd door wouter)
- [x]  melding traject als deze niet is geselecteerd (pop)
- [x] sortering nested gebieden
- [x] hydrovak id naar code
- [x] hoe wordt veenweide bepaald voor het taluud?
- [x] afronden verhang berekening
- [x] na toevoegen niet kunnen kiezen (hydrovak zonder andere keuzes)
- [x] bij dropdown zeggen wat het is
- [x] opmerking niet altijd opgeslagen
- [x] zijaanzicht met sp = distance 0
- [x] onder de grafiek met langsdoorsnede staat de as breedte [km], lengte  [km] lijkt me hier beter 
- [x] melding overdiepte als diepte niet bekend is (na toevoegen profiel) ?? (doet het volgens mij goed)

**Comment by stuart-minion** [comment]
@bastiaan-roos Wim en Rudy vroegen ook nog om de optie alleen dit hydrovak bij het dropdown menu waar we kiezen hoe ver een profiel wordt doorgetrokken

**Comment by bastiaan-roos** [comment]
veenweide wordt bepaald op basis van kolom 'grondsoort' in tabel 'kenmerken'. Als deze "veenweide" is, dan wordt de het maximum genomen tussen 3.0 en 'steilstetalud' uit de 'kenmerken' tabel.
steilste talud wordt bij inlezen bepaald op basis van DAMO db table 'hydroobjects met functie --> min(ws_talud_links, ws_talud_rechts)
