### ISSUE TITLE
Eerste stuk Wijdewormer geeft geen profielen

### ISSUE THREAD

**Issue by stuart-minion** [hhnk-git/legger#35]
![image](https://user-images.githubusercontent.com/48908991/67771167-16e9d500-fa58-11e9-81ab-4aa9eb9b097d.png)

**Comment by stuart-minion** [comment]
Er is geen debiet richting het gemaal...

**Comment by bastiaan-roos** [comment]
zat een 'loop' in het netwerk. Als deze wordt verwijderd werkt het weer.
