### ISSUE TITLE
Sommige watergangen krijgen geen verhang bij volledig begroeid

### ISSUE THREAD

**Issue by stuart-minion** [hhnk-git/legger#42]
Bijvoorbeeld OAF-CS-9004 / hydro_id 198169 van Marken

![image](https://user-images.githubusercontent.com/48908991/70712844-fe223f80-1ce4-11ea-8e4c-0409ade3feda.png)

**Comment by bastiaan-roos** [comment]
IN de database staat NULL. Gaat mis bij het berekenen. Profiel met grootste afmetingen heeft wel een verhang...

**Comment by bastiaan-roos** [comment]
de normatieve debieten konden negatief zijn. Op de één of andere manier kan de formule hier vaak wel goed mee omgaan, maar niet altijd. Normatieve flow absoluut gemaakt
