### ISSUE TITLE
Het berekende verhang klopt niet altijd

### ISSUE THREAD

**Issue by stuart-minion** [hhnk-git/legger#43]
Het lijkt alsof bij een laag verhang een andere formulering of gegevens gebruikt worden voor de berekening van verhang. Ik meen dat jij (Bastiaan) eens zei dat bos-bijkerk nog als minimum gold. Is dat nog steeds zo? Vervelend is alleen dat het berekende verhang in deze gevallen niet overeen komt met bos-bijkerk, manning of pitlo-griffioen.

Bijvoorbeeld OAF-CS-9208 / hydro_id 198373 op Marken.

Zie de Excel voor de handberekening.
[principe berekening hydraulische straal begroeiingsvarianten.xlsx](https://github.com/hhnk-git/legger/files/3955958/principe.berekening.hydraulische.straal.begroeiingsvarianten.xlsx)

**Comment by bastiaan-roos** [comment]
Vroeger keek hij naar bos en bijkerk en manning, maar nu alleen nog maar naar één. Dat is het dus niet.

**Comment by bastiaan-roos** [comment]
berekening klopt (test gemaakt). moet ergens in de loop zitten van het berekenen van de afmetingen...

**Comment by bastiaan-roos** [comment]
De excel input klopt niet, de bodembreedte is 0,5 ipv 0,7. Als dit wordt aangepast klopt het weer
