### ISSUE TITLE
Omgaan met dubbele hydroobject_id

### ISSUE THREAD

**Issue by stuart-minion** [hhnk-git/legger#55]
In Sommige DAMO databases zijn hydroobjecten met dubbele id's. Nu geeft dit een error bij het aanmaken van de database. Zou mooi zijn als hij hier mee om kan gaan. Waar worden de id gebruikt? Misschien een meldig terug geven van id's die zijn aangepast...

**Comment by bastiaan-roos** [comment]
Weer samenvoegen met een melding dat dat gedaan is (splitsen gebeurt bij modelleerproces)
