### ISSUE TITLE
hydroobjecten zonder debiet

### ISSUE THREAD

**Issue by stuart-minion** [hhnk-git/legger#57]
Nu wordt de view hydroobjects_kenmerken opgebouwd met een (INNER) JOIN waardoor niet alle objecten worden weergegeven in de verbonden hydrovakken en kenmerken. De view hydroobjects_selected_legger wordt opgebouwd met een OUTER JOIN. Hierdoor zijn in de overzichten wel alle hydroobjecten zichtbaar, maar in de kenmerken en bij het toewijzen niet. Ik weet niet of dit een bewuste keuze is. Ik weet ook niet wat we er mee moeten in het proces. Dit lijkt me een puntje om te bespreken.

**Comment by bastiaan-roos** [comment]
wouter: kijken waarom niet alle kenmerken bepaald
bastiaan: kijken of het kwaad kan

**Comment by stuart-minion** [comment]
De hydroobjecten worden meestal niet gemodelleerd. Alleen ze vallen nu weg uit de laag hydroobject kenmerken.

Dit was verwarrend omdat de ene laag meer ho's leek te hebben dan een andere. In de voortgang leek het daarom dat nog niet alles gedaan was, maar het lukte niet die ho's te vinden bij het toewijzen. Nu heb ik in de laag voortgang een extra typering gemaakt voor 'geen debiet' en is dit minder verwarrend. Deze issue kan denk ik worden gesloten.
