### ISSUE TITLE
Profielen kiezen waar dit evident is

### ISSUE THREAD

**Issue by bastiaan-roos** [hhnk-git/legger#9]
zodat invullen makkelijker wordt om hele polder te doen.
Voorstel: tertaire watergangen, advies laten begroeiien --> breedste profiel kiezen als er nog 10 % overbreedte is. stroomsnelheid lager is dan??

**Comment by bastiaan-roos** [comment]
idee: voorkeursdiepte per categorie

**Comment by stuart-minion** [comment]
Nieuwe uitgagngspunten zijn"
- op zoveel mogelijk plaatsen invullen
- gebruik standaardprofielen uit tabel (G:\02_Werkplaatsen\06_HYD\Projecten\HKC17012 Automatiseringstool leggerprofielen\06. Afgeleide gegevens\Legger_leggerplus_en_aanlegprofielen.xlsx)
- smooth op diepte, maar ook oog voor begroeiingsgraad

**Comment by stuart-minion** [comment]
- [ ] Varianten toevoegen aan elk hydrovak (keuze => in eerste instantie alle standaardprofielen aan elk hydrovak)
- [ ] Variant kiezen op basis van tabel (binnen debiet kiezen op basis van prio)
- [ ] Interface onder een knop zetten
- [ ] in interface: standaard profiel varianten herkenbaar en filterbaar in te kiezen varianten
- [ ] Standaard variant generatie: aanpassen hydraulisch/ legger plus profiel (debiet/ verhang vs fit + visualisatie). standaard regels voor overdiepte en minimale overbreedte (afhankelijk van grondsoort).
- [ ] smoothen op basis van diepte met netwerk (en mogelijk begroeiingsvarianten).
